// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(EmployeeDBContax))]
    [Migration("20251211153633_ModifymployeeSchema")]
    partial class ModifymployeeSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Data.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("DateofJoining")
                        .HasMaxLength(200)
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EmployeeAge")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DateofJoining = new DateTime(2021, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Development",
                            Description = "sdhfgyefywefewydfwtdfwtdfwtdrwdf",
                            Email = "uttam@gmail.com",
                            EmployeeAge = 29,
                            EmployeeName = "Uttam",
                            Experience = "5 yrs.",
                            Gender = "M"
                        },
                        new
                        {
                            EmployeeId = 2,
                            DateofJoining = new DateTime(2021, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Development",
                            Description = "sdhfgyefywefewydfwtdfwtdfwtdrwdf",
                            Email = "uttam@gmail.com",
                            EmployeeAge = 29,
                            EmployeeName = "Uttam Kumar",
                            Experience = "5 yrs.",
                            Gender = "M"
                        },
                        new
                        {
                            EmployeeId = 3,
                            DateofJoining = new DateTime(2021, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Development",
                            Description = "sdhfgyefywefewydfwtdfwtdfwtdrwdf",
                            Email = "uttam@gmail.com",
                            EmployeeAge = 29,
                            EmployeeName = "Uttam singh",
                            Experience = "5 yrs.",
                            Gender = "M"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
